### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by JeysonFlores** [jhass/crystal-gobject#83] opened 2021-03-23 19:54 UTC
Everytime I require this library it gives me this error:
```
Showing last frame. Use --error-trace for full trace.

In lib/gobject/generated/g_i_repository/repository.cr:171:116

 171 | __var1 = LibGIRepository.repository_require(@pointer.as(LibGIRepository::Repository*), namespace_.to_unsafe, version ? version.to_unsafe : nil, flags, pointerof(__var0))
                                                                                                                    ^
Error: argument 'version' of 'LibGIRepository#repository_require' must be Pointer(UInt8), not (Pointer(UInt8) | Nil)
```
My crystal version
```
Crystal 1.0.0 [dd40a2442] (2021-03-22)

LLVM: 10.0.0
Default target: x86_64-unknown-linux-gnu
```

I want to develop GTK in Crystal, it's a really straight-forward language, it's not full of verbose and it's really fast but these problems don't help me so much.
Thanks

**Comment by jhass** [comment] 2021-03-23 21:47
Duplicate of #82

**Closed by jhass** 2021-03-23 21:47 UTC

**Comment by JeysonFlores** [comment] 2021-03-24 01:44
*ª*
