### ISSUE TITLE
GTK4 support?

### ISSUE THREAD

**Issue by rubyFeedback** [jhass/crystal-gobject#104] opened 2022-09-17 16:48 UTC
Heya,

kou recently improved ruby-gtk4 support. I can now run gtk4 via ruby,
although many things confuse me still - the changed event handling
in gtk4 in particular.

Anyway - could crystal-gobject mention on the README which 
versions of gtk are supported, and if gtk4 support is not yet there,
to perhaps consider adding support for gtk4? At the least for simple
GUIs/projects. Buttons and texts alone already cover alot. I even 
experimented a bit (in ruby) by parsing --help of commandline 
scripts and then automatically create widgets based on that
e. g. "--set-foo=33" to have a spinner entry there, and what not.

**Comment by jhass** [comment] 2022-09-20 10:08
Have a look at https://github.com/hugopl/gtk4.cr

Otherwise duplicate of #87.

**Closed as completed by jhass** 2022-09-20 10:08 UTC
